server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive