server:
  port: 8081

spring:
  application:
    name: users-api
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}
springdoc:
  swagger-ui:
    path: /user-api-swagger
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
